"""采集诊断常量 — 失败类别与错误码枚举."""

from enum import StrEnum


class FailureCategory(StrEnum):
    """失败类别，用于 ingest_source_health 和 ingest_runtime_event."""

    CONFIG_ERROR = "CONFIG_ERROR"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SOURCE_TIMEOUT = "SOURCE_TIMEOUT"
    SOURCE_PARTIAL_FAILURE = "SOURCE_PARTIAL_FAILURE"
    DATA_INVALID = "DATA_INVALID"
    CACHE_UPDATE_FAILED = "CACHE_UPDATE_FAILED"
    SNAPSHOT_READ_FAILED = "SNAPSHOT_READ_FAILED"
    SNAPSHOT_EMPTY = "SNAPSHOT_EMPTY"
    SNAPSHOT_STALE = "SNAPSHOT_STALE"
    SNAPSHOT_INVALID = "SNAPSHOT_INVALID"
    PUBLISH_FAILED = "PUBLISH_FAILED"
    CYCLE_OVERRUN = "CYCLE_OVERRUN"
    JOB_EXECUTION_FAILED = "JOB_EXECUTION_FAILED"
    RESOURCE_EXHAUSTED = "RESOURCE_EXHAUSTED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"


class ErrorCode(StrEnum):
    """错误码枚举，用于结构化诊断."""

    # OPC UA
    OPCUA_CONNECTION_FAILED = "OPCUA_CONNECTION_FAILED"
    OPCUA_SESSION_CREATE_FAILED = "OPCUA_SESSION_CREATE_FAILED"
    OPCUA_READ_TIMEOUT = "OPCUA_READ_TIMEOUT"
    OPCUA_BAD_STATUS_CODE = "OPCUA_BAD_STATUS_CODE"
    OPCUA_PARTIAL_READ_FAILED = "OPCUA_PARTIAL_READ_FAILED"

    # Redis
    REDIS_CONNECTION_ERROR = "REDIS_CONNECTION_ERROR"
    REDIS_WRITE_TIMEOUT = "REDIS_WRITE_TIMEOUT"
    REDIS_MEMORY_FULL = "REDIS_MEMORY_FULL"

    # Kafka
    KAFKA_BROKER_UNAVAILABLE = "KAFKA_BROKER_UNAVAILABLE"
    KAFKA_ACK_TIMEOUT = "KAFKA_ACK_TIMEOUT"

    # Snapshot
    SNAPSHOT_EMPTY = "SNAPSHOT_EMPTY"
    SNAPSHOT_ALL_STALE = "SNAPSHOT_ALL_STALE"

    # Config
    CONFIG_PROTOCOL_ADAPTER_MISSING = "CONFIG_PROTOCOL_ADAPTER_MISSING"
    CONFIG_ENDPOINT_MISSING = "CONFIG_ENDPOINT_MISSING"
    CONFIG_TIMEOUT_INVALID = "CONFIG_TIMEOUT_INVALID"
    CONFIG_PROFILE_ITEMS_EMPTY = "CONFIG_PROFILE_ITEMS_EMPTY"
